### ISSUE TITLE
How to delete cached content for specific query ?

### ISSUE THREAD

**Issue by MarianoFacundoArch** [ilovepixelart/ts-cache-mongoose#141]
What would be the way to forcefully delete cached content for a specific query?

Thanks

**Comment by ilovepixelart** [comment]
Readme will be updated here https://github.com/ilovepixelart/ts-cache-mongoose/pull/143

**Comment by ilovepixelart** [comment]
Released in https://github.com/ilovepixelart/ts-cache-mongoose/releases/tag/v1.4.3
