### ISSUE TITLE
Usage of backend agnostic cache engine

### ISSUE THREAD

**Issue by angelhodar** [ilovepixelart/ts-cache-mongoose#182]
Hey! I was just watching for some package to cache some query responses and before reaching your repo I was thinking about using some standalone key-value storage agnostic package. I found keyv and unstorage to be very  easy to setup and they support multiple adapters out of the box, and keyv already has ttl support (havent checked unstorage). I see in the code that you created your own cache engine interface, so maybe its useful for you to let one of this packages to handle that for you! I suppose that you already studied it before creating this package but just in case.

**Comment by ilovepixelart** [comment]
Yep I want to have as less dependencies as possible when it comes to implementation of the package itself, and it was quite easy to implement.
