### ISSUE TITLE
ObjectIDs are not returned as strings when .lean() is called with a cache

### ISSUE THREAD

**Issue by bruce-bjorklund-sophos** [ilovepixelart/ts-cache-mongoose#191]
What is returned with a "findOne.cache().lean()" with no cache hydrated
  {
      _id: '660dd512e8532980bb5084e5'
    }
    
    
    
What is returned with a "findOne.cache().lean()" with  the cache hydrated:
  {
      _id: new ObjectId("660dd512e8532980bb5084e5"),
    }
    
I would expect that we would get only JSON back if we called lean().

thoughts?

**Comment by ilovepixelart** [comment]
I'm concerned about first statement, but lean !== json
Here is example in mongoose playground: https://playground.mongoosejs.io/#YXdhaXQgbW9uZ29vc2UuY29ubmVjdCgnbW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9tb25nb29zZV90ZXN0Jyk7CmNvbnN0IHNjaGVtYSA9IG5ldyBtb25nb29zZS5TY2hlbWEoeyBuYW1lOiBTdHJpbmcgfSk7CmNvbnN0IFVzZXIgPSBtb25nb29zZS5tb2RlbCgnVXNlcicsIHNjaGVtYSk7Cgpjb25zdCBjcmVhdGVkID0gYXdhaXQgVXNlci5jcmVhdGUoeyBuYW1lOiAnU3RldmUnIH0pCmNvbnN0IGxlYW4gPSBhd2FpdCBVc2VyLmZpbmRCeUlkKGNyZWF0ZWQuX2lkKS5sZWFuKCk7Cgpjb25zb2xlLmxvZyhsZWFuKQpjb25zb2xlLmxvZyh0eXBlb2YgbGVhbi5faWQp

**Comment by bruce-bjorklund-sophos** [comment]
Yeah you are right, it is valid JSON, but what we are expecting is the _id to be a string, not an ObjectID.

I went through your code and it looks like in the Redis driver, and you do a thing where if the value is a string, and a UUID you cast it into a ObjectID. 

In Mongoose, if we don't use lean() we get back UUIDs with ObjectID types... but if we use lean() we get back full JSON. So there are no methods like .toJSON(). TBH I think the decision to cast every ObjectID string into a objectID class breaks the implementation of lean()

**Comment by ilovepixelart** [comment]
Did you check example I gave you in playground lean returns _id as object when using lean. This is why I cast to object be cause lean not returning ids as strings period

**Comment by bruce-bjorklund-sophos** [comment]
Oh you know what I think it is?

We have the schema where the _id is a string... but we generate an ObjectID for it:

` const UserSchema = new Schema<IUser>({
  _id: String,
  organization_id: String,
});`

The redis engine will cast any string that is an ObjectID match regardless of the schema definition

**Comment by ilovepixelart** [comment]
Now thats makes total sense now!

**Comment by bruce-bjorklund-sophos** [comment]
Yeah... Yeah I completely agree with you on that this is non-standard - I'm just like, the janitor. 

I think the right thing to do would be migrate to the standard, but that LOE is too much. Would be cool if the engine used the schema for type casting but not sure what the LOE would be on that or if its even possible.

**Comment by ilovepixelart** [comment]
Yep I did this default casting due to aggregate inability to properly hydrate:
https://github.com/Automattic/mongoose/issues/8784#issuecomment-615898559

And for cases like district, will check what we can do, but it's not a trivial stuff of just removing casting

But if you have sufficient ram on pod/service you can switch driver to in memory, this will solve your issue since in memory driver stores object as is without stringify etc

**Comment by ilovepixelart** [comment]
Will link here issue I created in mongoose official repo, looks like propper migration is not happening even on Query
https://github.com/Automattic/mongoose/issues/14503

**Comment by ilovepixelart** [comment]
PR for serialization in redis engine: https://github.com/ilovepixelart/ts-cache-mongoose/pull/198

**Comment by ilovepixelart** [comment]
Released in: https://github.com/ilovepixelart/ts-cache-mongoose/releases/tag/v1.6.0
