### ISSUE TITLE
Library seems broken

### ISSUE THREAD

**Issue by rrigoni** [ilovepixelart/ts-cache-mongoose#216]
Node 20, mongoose 8.5.0, ts-cache-mongoose 1.6.3

Seeing this error: 

````
ERROR   :     Cannot read properties of undefined (reading 'prototype') - TypeError: Cannot read properties of undefined (reading 'prototype')
    at extendQuery (/node_modules/ts-cache-mongoose/src/extend/aggregate.ts:8:43)
    at Function.init (node_modules/ts-cache-mongoose/src/plugin.ts:47:22)
````

Configuration 
````
cache.init(mongoose, {
      defaultTTL: "60 seconds",
      engine: "memory",
    });
````

**Comment by ilovepixelart** [comment]
Not sure what you doing there...
Here is working example you can run on node 20 that uses mongoose 8.5.0, ts-cache-mongoose 1.6.3:
https://github.com/ilovepixelart/ts-express-swc
```bash
npm run build:ts
npm run start
```
or in dev mode 
```bash
npm run dev
```
Then open localhost:3000/users and check the console I enabled debug mode o
