### ISSUE TITLE
Refactor clear method of CacheMongoose class

### ISSUE THREAD

**Issue by ozanbaskan** [ilovepixelart/ts-cache-mongoose#66]
**Is your feature request related to a problem? Please describe.**
Instead of checking whether the key is falsy or not we can check if it is undefined, so I can remove a key which is an empty string.

**Describe the solution you'd like**
I want to be able to pass an empty string and clear that key.

**Describe alternatives you've considered**
`if (customKey != null)` or `if (customKey !== undefined)` instead of `if (customKey)`

**Comment by ilovepixelart** [comment]
Good Idea, but why you need an empty string key?

**Comment by ilovepixelart** [comment]
PR: https://github.com/ilovepixelart/ts-cache-mongoose/pull/67

**Comment by ilovepixelart** [comment]
Released: https://github.com/ilovepixelart/ts-cache-mongoose/releases/tag/v1.0.8
